---
- name: Install MongoDB 3.2
  hosts: all
  become: true
  tasks:
    - name: Add an apt key
      apt_key:
        keyserver: keyserver.ubuntu.com
        id: EA312927

    - name: add repo
      apt_repository:
        repo: deb http://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/3.2 multiverse 
        state: present
        filename: mongodb-org-3.2.list

    - name: Add package
      apt:
        name: mongodb-org
        update_cache: yes
        state: latest

    - name: Enable mongod
      systemd:
        enabled: yes
        name: mongod
