---
dependency:
  name: galaxy
driver:
  name: gce
lint:
  name: yamllint
platforms:
  - name: instance
    zone: us-west1-a
    machine_type: f1-micro
    image: ubuntu-1604-lts
    state: present
#    service_account_email: "fedderro@gmail.com"
#    credentials_file: "/home/user/Documents/keys/Infra-ffa2344a9cec.json"
#    project_id: "infra-220718"
    zone: europe-west1-b
#    service_account_permissions: useraccounts-rw
provisioner:
  name: ansible
  lint:
    name: ansible-lint
scenario:
  name: default
verifier:
  name: testinfra
  lint:
    name: flake8
